version: "3.9"
services:
  redis:
    image: redis:alpine
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - ./drivers.db/drivers.db:/app/drivers.db
  processor:
    build:
      context: ./processor
      dockerfile: Dockerfile.processor
    depends_on:
      - redis
