name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Шаг 1: Сборка и тесты
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests

  # Шаг 2: Сборка и публикация Docker-образа для API
  build-api-docker:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v4
        with:
          context: api/
          file: api/Dockerfile.api
          push: true
          tags: your-dockerhub-username/order-processing-api:latest

  # Шаг 3: Сборка и публикация Docker-образа для Processor
  build-processor-docker:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Processor Docker image
        uses: docker/build-push-action@v4
        with:
          context: processor/
          file: processor/Dockerfile.processor
          push: true
          tags: your-dockerhub-username/order-processing-processor:latest

  # Шаг 4: Деплой на сервер (опционально, если у вас есть сервер)
  deploy:
    runs-on: ubuntu-latest
    needs: [build-api-docker, build-processor-docker]

    steps:
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} user@your-server.com << 'EOF'
            docker pull your-dockerhub-username/order-processing-api:latest
            docker pull your-dockerhub-username/order-processing-processor:latest
            docker stop orderprocessing-api || true
            docker rm orderprocessing-api || true
            docker run -d --name orderprocessing-api -p 80:80 your-dockerhub-username/order-processing-api:latest
            docker stop orderprocessing-processor || true
            docker rm orderprocessing-processor || true
            docker run -d --name orderprocessing-processor your-dockerhub-username/order-processing-processor:latest
          EOF
